
package com.person;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonProvisionWSService", targetNamespace = "http://ws.person.training.ee.java.com/", wsdlLocation = "http://localhost:8080/eetraining/PersonProvisionWS?wsdl")
public class PersonProvisionWSService
    extends Service
{

    private final static URL PERSONPROVISIONWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONPROVISIONWSSERVICE_EXCEPTION;
    private final static QName PERSONPROVISIONWSSERVICE_QNAME = new QName("http://ws.person.training.ee.java.com/", "PersonProvisionWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/eetraining/PersonProvisionWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONPROVISIONWSSERVICE_WSDL_LOCATION = url;
        PERSONPROVISIONWSSERVICE_EXCEPTION = e;
    }

    public PersonProvisionWSService() {
        super(__getWsdlLocation(), PERSONPROVISIONWSSERVICE_QNAME);
    }

    public PersonProvisionWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONPROVISIONWSSERVICE_QNAME, features);
    }

    public PersonProvisionWSService(URL wsdlLocation) {
        super(wsdlLocation, PERSONPROVISIONWSSERVICE_QNAME);
    }

    public PersonProvisionWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONPROVISIONWSSERVICE_QNAME, features);
    }

    public PersonProvisionWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonProvisionWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonProvisionWS
     */
    @WebEndpoint(name = "PersonProvisionWSPort")
    public PersonProvisionWS getPersonProvisionWSPort() {
        return super.getPort(new QName("http://ws.person.training.ee.java.com/", "PersonProvisionWSPort"), PersonProvisionWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonProvisionWS
     */
    @WebEndpoint(name = "PersonProvisionWSPort")
    public PersonProvisionWS getPersonProvisionWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.person.training.ee.java.com/", "PersonProvisionWSPort"), PersonProvisionWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONPROVISIONWSSERVICE_EXCEPTION!= null) {
            throw PERSONPROVISIONWSSERVICE_EXCEPTION;
        }
        return PERSONPROVISIONWSSERVICE_WSDL_LOCATION;
    }

}
