
package com.person;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonProvisionWS", targetNamespace = "http://ws.person.training.ee.java.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonProvisionWS {


    /**
     * 
     * @param username
     * @return
     *     returns com.person.Person
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "get", targetNamespace = "http://ws.person.training.ee.java.com/", className = "com.person.Get")
    @ResponseWrapper(localName = "getResponse", targetNamespace = "http://ws.person.training.ee.java.com/", className = "com.person.GetResponse")
    public Person get(
        @WebParam(name = "username", targetNamespace = "")
        String username);

    /**
     * 
     * @return
     *     returns java.util.List<com.person.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getall", targetNamespace = "http://ws.person.training.ee.java.com/", className = "com.person.Getall")
    @ResponseWrapper(localName = "getallResponse", targetNamespace = "http://ws.person.training.ee.java.com/", className = "com.person.GetallResponse")
    public List<Person> getall();

    /**
     * 
     * @param person
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://ws.person.training.ee.java.com/", className = "com.person.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://ws.person.training.ee.java.com/", className = "com.person.AddResponse")
    public String add(
        @WebParam(name = "person", targetNamespace = "")
        Person person);

}
